language: python

python:
  - '3.4'
 
before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq python-dbus python-pip

install:
 - pip install pyserial
 - pip install platformio
 - platformio lib install 4
 - platformio lib install 136

script:
 - cd python
 - python -m py_compile "sd.py"
 - cd ..
 - cd arduino
 - cd lcd
 - platformio run
 - cd ..
 - cd ir
 - platformio run
