language: python

python:
  - '2.7'
  
before_install:
 - sudo echo "deb http://ppa.launchpad.net/fkrull/deadsnakes/ubuntu precise main" | sudo tee -a /etc/apt/sources.list
 - pwd
 - sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys DB82666C
 - sudo apt-get update -qq
 - sudo apt-get install -qq python-dbus python3.4 python-pip

install:
 - pip install pyserial
 - pip install platformio
 - platformio lib install 4
 - platformio lib install 136

script:
 - cd python
 - python -m py_compile "sd.py"
 - cd ..
 - cd arduino
 - cd lcd
 - platformio run
 - cd ..
 - cd ir
 - platformio run
